<script src="{{ getThemeAsset() }}/assets/js/jquery-2.1.4.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
<script src="{{ getThemeAsset() }}/assets/js/jquery.srcipts.min.js"></script>
<script src="{{ getThemeAsset() }}/assets/js/jquery.nivo.slider.pack.js"></script>
<script src="{{ getThemeAsset() }}/assets/js/jquery.dlmenu.min.js"></script>
<script src="{{ getThemeAsset() }}/assets/style-switcher/styleSwitcher.js"></script>
<script src="{{ getThemeAsset() }}/assets/owl-carousel/owl.carousel.min.js"></script>
<script src="{{ getThemeAsset() }}/assets/masterslider/masterslider.min.js"></script>
<script src="{{ getThemeAsset() }}/assets/js/jquery.dlmenu.min.js"></script>
<script src="{{ getThemeAsset() }}/assets/js/include.js"></script>